language: node_js
node_js: '0.12'
sudo: false
addons:
  sauce_connect: true
env:
  global:
  - secure: au7XtmQDR14Sbp/lvXkRWpW+WDtv1JnWkaxwnzsEAbE/49hPXvPi6LDMrexDPq4uc4ENHwgCJa/SR6yYBZmWSUS6TotxrRpSfi79V8AvB31lcQrHgtssOLcTJvOrSQPjWK+a9O9bdb/zS8s/5wnE9Y06A59vSHd482BR7FX9nCs=
  - secure: nJzTL/VeaVaqWg+qOrDOVzOq/zr0KcVli2AmL6JYpNfSLDMk5ZFR8Qs2ZUXkerJY36KEzrZnYQ9SDMkhYtTUf6SpH3MoMDcs79wOMVBWKHdYX5jf1aIuE+75pNU15HK0vwtT1wV5uZurrkx46K/EKobjspIOy0Qs/jAQ8AVKuoE=
  - COMMAND='npm run test'
  matrix:
  - BROWSER=PhantomJS
  - BROWSER=SL_Chrome
  - BROWSER=SL_Firefox
  - BROWSER=SL_Safari
  - BROWSER=SL_IE_8
  - BROWSER=SL_IE_9
  - BROWSER=SL_IE_10
  - BROWSER=SL_IE_11
matrix:
  allow_failures:
  - env: BROWSER=SL_IE_8
  include:
  - env: COMMAND='npm run lint'
script:
- '[ "${TRAVIS_PULL_REQUEST}" != "false" -a "${BROWSER}" != "PhantomJS" ] && true || ${COMMAND}'
cache:
  directories:
  - node_modules
